basePath: /v2
host: node01
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Simple API for metric collecting
  version: "1.0"
paths:
  /error:
    get:
      produces:
      - application/json
      summary: Produce error
  /metrics:
    get:
      produces:
      - application/json
      summary: Retrieve metrics
  /ping:
    get:
      produces:
      - application/json
      summary: Ping
  /repair:
    get:
      produces:
      - application/json
      summary: Repair the error
swagger: "2.0"
